<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="../../src/Mathesis.Symbolics/Mathesis.Symbolics.csproj" />
    <ProjectReference Include="../Mathesis.Testing/Mathesis.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../corpus/**" Link="corpus/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
