// Typed handles for the knowledge catalog. Run: dotnet run eng/gen-knowledge.cs [-- --check]
// Reads every knowledge/**/*.mlaw file and writes src/Mathesis.Knowledge/Catalog.g.cs: a static class per entry kind (Laws, Formulas, ...)
// with nested classes for the domain and topic and one EntryId constant per entry, e.g. Laws.Algebra.Exp.ProductOfPowers.
// With --check nothing is written; the exit code is 1 when the checked-in file is out of date.
#:project ../src/Mathesis.Knowledge/Mathesis.Knowledge.csproj

using System.Globalization;
using System.Text;
using Mathesis.Knowledge;

var root = Directory.GetCurrentDirectory();
while (root is not null && !File.Exists(Path.Combine(root, "Mathesis.slnx"))) root = Path.GetDirectoryName(root);
if (root is null)
{
    Console.Error.WriteLine("Run from inside the repository (Mathesis.slnx not found).");
    return 1;
}

var files = Directory.GetFiles(Path.Combine(root, "knowledge"), "*.mlaw", SearchOption.AllDirectories)
    .Select(f => (Name: Path.GetRelativePath(Path.Combine(root, "knowledge"), f).Replace('\\', '/'), Text: File.ReadAllText(f)))
    .ToList();
var catalog = KnowledgeBase.Load(files);
if (catalog.Errors.Any())
{
    foreach (var error in catalog.Errors) Console.Error.WriteLine(error);
    Console.Error.WriteLine("The catalog has errors; fix them before generating handles.");
    return 1;
}

var domainNames = new Dictionary<string, string>(StringComparer.Ordinal)
{
    ["alg"] = "Algebra", ["trig"] = "Trigonometry", ["logic"] = "Logic", ["pre"] = "PreCalculus", ["calc"] = "Calculus",
    ["ode"] = "DifferentialEquations", ["linalg"] = "LinearAlgebra", ["fin"] = "FiniteMath", ["num"] = "NumericalAnalysis", ["conv"] = "Conventions",
};
var kindClasses = new (EntryKind Kind, string Class)[]
{
    (EntryKind.Definition, "Definitions"), (EntryKind.Axiom, "Axioms"), (EntryKind.Law, "Laws"), (EntryKind.Theorem, "Theorems"),
    (EntryKind.Formula, "Formulas"), (EntryKind.Pattern, "Patterns"), (EntryKind.Method, "Methods"), (EntryKind.Convention, "Conventions"),
};

string Pascal(string kebab)
{
    var sb = new StringBuilder();
    foreach (var part in kebab.Split('-', StringSplitOptions.RemoveEmptyEntries))
    {
        sb.Append(char.ToUpperInvariant(part[0])).Append(part, 1, part.Length - 1);
    }
    var name = sb.ToString();
    return name.Length == 0 || char.IsDigit(name[0]) ? "_" + name : name;
}

var output = new StringBuilder();
void Line(string text = "") => output.Append(text).Append('\n');
Line("// <auto-generated>");
Line("// Generated by eng/gen-knowledge.cs from knowledge/**/*.mlaw. Do not edit; run: dotnet run eng/gen-knowledge.cs");
Line("// </auto-generated>");
Line();
Line("namespace Mathesis.Knowledge;");

foreach (var (kind, className) in kindClasses)
{
    var entries = catalog.ByKind(kind).ToList();
    if (entries.Count == 0) continue;
    Line();
    Line($"/// <summary>Handles of the catalog entries of kind {kind.ToString().ToLowerInvariant()}.</summary>");
    Line($"public static class {className}");
    Line("{");

    // Entries of the conv domain have two-segment IDs and live directly in the class; the others are grouped by domain and topic.
    var direct = entries.Where(e => e.Id.Value.Count(c => c == '.') == 1).ToList();
    var used = new HashSet<string>(StringComparer.Ordinal);
    foreach (var e in direct)
    {
        var member = Unique(Pascal(e.Id.Value[(e.Id.Value.IndexOf('.', StringComparison.Ordinal) + 1)..]), used, className);
        Line($"    /// <summary>{Escape(e.Name)}.</summary>");
        Line($"    public static readonly EntryId {member} = new(\"{e.Id}\");");
        Line();
    }

    var byDomain = entries.Where(e => e.Id.Value.Count(c => c == '.') == 2).GroupBy(e => e.Id.Domain).OrderBy(g => g.Key, StringComparer.Ordinal);
    foreach (var domain in byDomain)
    {
        var domainClass = domainNames.TryGetValue(domain.Key, out var friendly) ? friendly : Pascal(domain.Key);
        Line($"    /// <summary>{domainClass}.</summary>");
        Line($"    public static class {domainClass}");
        Line("    {");
        foreach (var topic in domain.GroupBy(e => e.Id.Value.Split('.')[1]).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var topicClass = Unique(Pascal(topic.Key), new HashSet<string>([domainClass]), domainClass);
            var members = new HashSet<string>(StringComparer.Ordinal);
            Line($"        /// <summary>{Escape(topic.First().DomainTitle)}.</summary>");
            Line($"        public static class {topicClass}");
            Line("        {");
            foreach (var e in topic.OrderBy(x => x.Id.Value, StringComparer.Ordinal))
            {
                var member = Unique(Pascal(e.Id.Value.Split('.')[2]), members, topicClass);
                Line($"            /// <summary>{Escape(e.Name)}.</summary>");
                Line($"            public static readonly EntryId {member} = new(\"{e.Id}\");");
                Line();
            }
            Line("        }");
            Line();
        }
        Line("    }");
        Line();
    }
    Line("}");
}

var text = System.Text.RegularExpressions.Regex.Replace(output.ToString(), "\n\n( *)[}]", "\n$1}");
var target = Path.Combine(root, "src", "Mathesis.Knowledge", "Catalog.g.cs");
var current = File.Exists(target) ? File.ReadAllText(target).Replace("\r\n", "\n", StringComparison.Ordinal) : string.Empty;
if (args.Contains("--check"))
{
    if (current == text)
    {
        Console.WriteLine("Catalog.g.cs is up to date.");
        return 0;
    }
    Console.Error.WriteLine("Catalog.g.cs is out of date; run: dotnet run eng/gen-knowledge.cs");
    return 1;
}
File.WriteAllText(target, text, new UTF8Encoding(false));
Console.WriteLine($"Wrote {Path.GetRelativePath(root, target)} with {catalog.Count} handles.");
return 0;

static string Escape(string s) => s.Replace("&", "&amp;", StringComparison.Ordinal).Replace("<", "&lt;", StringComparison.Ordinal).Replace(">", "&gt;", StringComparison.Ordinal);

// A member may not share the name of its enclosing class or of another member of that class.
static string Unique(string name, HashSet<string> used, string enclosing)
{
    if (name == enclosing) name += "Entry";
    var candidate = name;
    for (var i = 2; !used.Add(candidate); i++) candidate = name + i.ToString(CultureInfo.InvariantCulture);
    return candidate;
}
