// <auto-generated>
// Generated by eng/gen-knowledge.cs from knowledge/**/*.mlaw. Do not edit; run: dotnet run eng/gen-knowledge.cs
// </auto-generated>

namespace Mathesis.Knowledge;

/// <summary>Handles of the catalog entries of kind definition.</summary>
public static class Definitions
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Equations.</summary>
        public static class Eq
        {
            /// <summary>Extraneous solution.</summary>
            public static readonly EntryId Extraneous = new("alg.eq.extraneous");
        }

        /// <summary>Laws of exponents.</summary>
        public static class Exp
        {
            /// <summary>Scientific notation.</summary>
            public static readonly EntryId SciNotation = new("alg.exp.sci-notation");
        }

        /// <summary>Factoring.</summary>
        public static class Factor
        {
            /// <summary>Content and primitive part.</summary>
            public static readonly EntryId ContentPrimitive = new("alg.factor.content-primitive");

            /// <summary>Irreducible over the reals.</summary>
            public static readonly EntryId IrreducibleQuadratic = new("alg.factor.irreducible-quadratic");
        }

        /// <summary>Logarithms.</summary>
        public static class Log
        {
            /// <summary>Definition of the logarithm.</summary>
            public static readonly EntryId Def = new("alg.log.def");
        }

        /// <summary>Percents.</summary>
        public static class Pct
        {
            /// <summary>Percent.</summary>
            public static readonly EntryId Def = new("alg.pct.def");
        }

        /// <summary>Polynomial division and roots.</summary>
        public static class Poly
        {
            /// <summary>Multiplicity of a root.</summary>
            public static readonly EntryId Multiplicity = new("alg.poly.multiplicity");
        }

        /// <summary>Quadratics.</summary>
        public static class Quad
        {
            /// <summary>Discriminant.</summary>
            public static readonly EntryId Discriminant = new("alg.quad.discriminant");

            /// <summary>Standard form of a quadratic.</summary>
            public static readonly EntryId StandardForm = new("alg.quad.standard-form");
        }

        /// <summary>Radicals.</summary>
        public static class Rad
        {
            /// <summary>Real n-th root.</summary>
            public static readonly EntryId NthDef = new("alg.rad.nth-def");

            /// <summary>Principal square root.</summary>
            public static readonly EntryId SqrtDef = new("alg.rad.sqrt-def");
        }

        /// <summary>Rational expressions.</summary>
        public static class Rat
        {
            /// <summary>Domain of a rational expression.</summary>
            public static readonly EntryId Domain = new("alg.rat.domain");

            /// <summary>Proper rational function.</summary>
            public static readonly EntryId Proper = new("alg.rat.proper");
        }
    }

    /// <summary>Calculus.</summary>
    public static class Calculus
    {
        /// <summary>Derivative definition and rules.</summary>
        public static class Deriv
        {
            /// <summary>Derivative.</summary>
            public static readonly EntryId Def = new("calc.deriv.def");

            /// <summary>Derivative at a point (alternative form).</summary>
            public static readonly EntryId DefAlt = new("calc.deriv.def-alt");
        }

        /// <summary>Improper integrals.</summary>
        public static class Improper
        {
            /// <summary>Infinite interval.</summary>
            public static readonly EntryId Type1 = new("calc.improper.type1");

            /// <summary>Discontinuous integrand.</summary>
            public static readonly EntryId Type2 = new("calc.improper.type2");
        }

        /// <summary>Integration techniques.</summary>
        public static class Int
        {
            /// <summary>Antiderivative.</summary>
            public static readonly EntryId Antiderivative = new("calc.int.antiderivative");
        }

        /// <summary>Limits.</summary>
        public static class Lim
        {
            /// <summary>Limit at infinity.</summary>
            public static readonly EntryId AtInfinity = new("calc.lim.at-infinity");

            /// <summary>Epsilon-delta limit.</summary>
            public static readonly EntryId Def = new("calc.lim.def");

            /// <summary>Indeterminate forms.</summary>
            public static readonly EntryId IndeterminateForms = new("calc.lim.indeterminate-forms");

            /// <summary>Infinite limit.</summary>
            public static readonly EntryId Infinite = new("calc.lim.infinite");
        }

        /// <summary>Taylor series.</summary>
        public static class Series
        {
            /// <summary>Taylor series.</summary>
            public static readonly EntryId Taylor = new("calc.series.taylor");
        }
    }

    /// <summary>LinearAlgebra.</summary>
    public static class LinearAlgebra
    {
        /// <summary>Determinants.</summary>
        public static class Det
        {
            /// <summary>Leibniz formula.</summary>
            public static readonly EntryId Leibniz = new("linalg.det.leibniz");
        }

        /// <summary>Linear systems.</summary>
        public static class Sys
        {
            /// <summary>Row echelon form.</summary>
            public static readonly EntryId Ref = new("linalg.sys.ref");

            /// <summary>Reduced row echelon form.</summary>
            public static readonly EntryId Rref = new("linalg.sys.rref");
        }
    }

    /// <summary>Trigonometry.</summary>
    public static class Trigonometry
    {
        /// <summary>Definitions of the trigonometric functions.</summary>
        public static class Def
        {
            /// <summary>Cotangent.</summary>
            public static readonly EntryId Cot = new("trig.def.cot");

            /// <summary>Coterminal angles.</summary>
            public static readonly EntryId Coterminal = new("trig.def.coterminal");

            /// <summary>Cosecant.</summary>
            public static readonly EntryId Csc = new("trig.def.csc");

            /// <summary>Quadrant signs (ASTC).</summary>
            public static readonly EntryId QuadrantSigns = new("trig.def.quadrant-signs");

            /// <summary>Radian measure.</summary>
            public static readonly EntryId Radian = new("trig.def.radian");

            /// <summary>Reference angle.</summary>
            public static readonly EntryId ReferenceAngle = new("trig.def.reference-angle");

            /// <summary>Right-triangle ratios.</summary>
            public static readonly EntryId RightTriangle = new("trig.def.right-triangle");

            /// <summary>Secant.</summary>
            public static readonly EntryId Sec = new("trig.def.sec");

            /// <summary>Tangent.</summary>
            public static readonly EntryId Tan = new("trig.def.tan");

            /// <summary>Unit-circle definition.</summary>
            public static readonly EntryId UnitCircle = new("trig.def.unit-circle");
        }

        /// <summary>Inverse trigonometric functions.</summary>
        public static class Inv
        {
            /// <summary>Arccosine.</summary>
            public static readonly EntryId ArccosDef = new("trig.inv.arccos-def");

            /// <summary>Arccotangent.</summary>
            public static readonly EntryId ArccotDef = new("trig.inv.arccot-def");

            /// <summary>Arcsine.</summary>
            public static readonly EntryId ArcsinDef = new("trig.inv.arcsin-def");

            /// <summary>Arctangent.</summary>
            public static readonly EntryId ArctanDef = new("trig.inv.arctan-def");

            /// <summary>Two-argument arctangent.</summary>
            public static readonly EntryId Atan2Def = new("trig.inv.atan2-def");
        }

        /// <summary>Angle units and circular measure.</summary>
        public static class Unit
        {
            /// <summary>Linear and angular speed.</summary>
            public static readonly EntryId LinearSpeed = new("trig.unit.linear-speed");
        }
    }
}

/// <summary>Handles of the catalog entries of kind axiom.</summary>
public static class Axioms
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Field and order axioms.</summary>
        public static class Ax
        {
            /// <summary>Associativity of addition.</summary>
            public static readonly EntryId AddAssoc = new("alg.ax.add-assoc");

            /// <summary>Commutativity of addition.</summary>
            public static readonly EntryId AddComm = new("alg.ax.add-comm");

            /// <summary>Additive identity.</summary>
            public static readonly EntryId AddIdentity = new("alg.ax.add-identity");

            /// <summary>Additive inverse.</summary>
            public static readonly EntryId AddInverse = new("alg.ax.add-inverse");

            /// <summary>Distributive property.</summary>
            public static readonly EntryId Distributive = new("alg.ax.distributive");

            /// <summary>Associativity of multiplication.</summary>
            public static readonly EntryId MulAssoc = new("alg.ax.mul-assoc");

            /// <summary>Commutativity of multiplication.</summary>
            public static readonly EntryId MulComm = new("alg.ax.mul-comm");

            /// <summary>Multiplicative identity.</summary>
            public static readonly EntryId MulIdentity = new("alg.ax.mul-identity");

            /// <summary>Multiplicative inverse.</summary>
            public static readonly EntryId MulInverse = new("alg.ax.mul-inverse");

            /// <summary>Non-triviality.</summary>
            public static readonly EntryId ZeroNeOne = new("alg.ax.zero-ne-one");
        }

        /// <summary>Properties of equality.</summary>
        public static class Eqprop
        {
            /// <summary>Reflexive property of equality.</summary>
            public static readonly EntryId Reflexive = new("alg.eqprop.reflexive");

            /// <summary>Substitution property of equality.</summary>
            public static readonly EntryId Substitution = new("alg.eqprop.substitution");

            /// <summary>Symmetric property of equality.</summary>
            public static readonly EntryId Symmetric = new("alg.eqprop.symmetric");

            /// <summary>Transitive property of equality.</summary>
            public static readonly EntryId Transitive = new("alg.eqprop.transitive");
        }

        /// <summary>Order properties of the real numbers.</summary>
        public static class Order
        {
            /// <summary>Archimedean property.</summary>
            public static readonly EntryId Archimedean = new("alg.order.archimedean");

            /// <summary>Transitivity of &lt;.</summary>
            public static readonly EntryId Transitive = new("alg.order.transitive");

            /// <summary>Trichotomy.</summary>
            public static readonly EntryId Trichotomy = new("alg.order.trichotomy");
        }
    }
}

/// <summary>Handles of the catalog entries of kind law.</summary>
public static class Laws
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Absolute value.</summary>
        public static class Abs
        {
            /// <summary>Definition of absolute value.</summary>
            public static readonly EntryId Def = new("alg.abs.def");

            /// <summary>Absolute-value equation.</summary>
            public static readonly EntryId Eq = new("alg.abs.eq");

            /// <summary>Equal absolute values.</summary>
            public static readonly EntryId EqAbs = new("alg.abs.eq-abs");

            /// <summary>Symmetry of absolute value.</summary>
            public static readonly EntryId Even = new("alg.abs.even");

            /// <summary>Absolute-value greater-than inequality.</summary>
            public static readonly EntryId Gt = new("alg.abs.gt");

            /// <summary>Absolute-value less-than inequality.</summary>
            public static readonly EntryId Lt = new("alg.abs.lt");

            /// <summary>Absolute value as a maximum.</summary>
            public static readonly EntryId Max = new("alg.abs.max");

            /// <summary>Non-negativity of absolute value.</summary>
            public static readonly EntryId Nonneg = new("alg.abs.nonneg");

            /// <summary>Absolute value of a power.</summary>
            public static readonly EntryId Power = new("alg.abs.power");

            /// <summary>Absolute value of a product.</summary>
            public static readonly EntryId Product = new("alg.abs.product");

            /// <summary>Absolute value of a quotient.</summary>
            public static readonly EntryId Quotient = new("alg.abs.quotient");

            /// <summary>Reverse triangle inequality.</summary>
            public static readonly EntryId ReverseTriangle = new("alg.abs.reverse-triangle");

            /// <summary>Square and absolute value.</summary>
            public static readonly EntryId Square = new("alg.abs.square");

            /// <summary>Triangle inequality.</summary>
            public static readonly EntryId Triangle = new("alg.abs.triangle");

            /// <summary>Absolute value is zero only at zero.</summary>
            public static readonly EntryId Zero = new("alg.abs.zero");
        }

        /// <summary>Complex numbers: arithmetic.</summary>
        public static class Cplx
        {
            /// <summary>Conjugate product.</summary>
            public static readonly EntryId ConjProduct = new("alg.cplx.conj-product");

            /// <summary>Conjugate of a sum and of a product.</summary>
            public static readonly EntryId ConjSum = new("alg.cplx.conj-sum");

            /// <summary>Division by the conjugate.</summary>
            public static readonly EntryId Div = new("alg.cplx.div");

            /// <summary>Equality of complex numbers.</summary>
            public static readonly EntryId Equality = new("alg.cplx.equality");

            /// <summary>The imaginary unit.</summary>
            public static readonly EntryId ISquared = new("alg.cplx.i-squared");

            /// <summary>Modulus.</summary>
            public static readonly EntryId Modulus = new("alg.cplx.modulus");

            /// <summary>Multiplication of complex numbers.</summary>
            public static readonly EntryId Mul = new("alg.cplx.mul");

            /// <summary>Powers of i.</summary>
            public static readonly EntryId PowersOfI = new("alg.cplx.powers-of-i");

            /// <summary>Square root of a negative number.</summary>
            public static readonly EntryId SqrtNeg = new("alg.cplx.sqrt-neg");

            /// <summary>Standard form.</summary>
            public static readonly EntryId StandardForm = new("alg.cplx.standard-form");
        }

        /// <summary>Properties of equality.</summary>
        public static class Eqprop
        {
            /// <summary>Addition property of equality.</summary>
            public static readonly EntryId Add = new("alg.eqprop.add");

            /// <summary>Additive cancellation.</summary>
            public static readonly EntryId CancelAdd = new("alg.eqprop.cancel-add");

            /// <summary>Multiplicative cancellation.</summary>
            public static readonly EntryId CancelMul = new("alg.eqprop.cancel-mul");

            /// <summary>Multiplication property of equality.</summary>
            public static readonly EntryId Mul = new("alg.eqprop.mul");
        }

        /// <summary>Laws of exponents.</summary>
        public static class Exp
        {
            /// <summary>Equal powers, equal bases.</summary>
            public static readonly EntryId EqualBases = new("alg.exp.equal-bases");

            /// <summary>Even power of a negative.</summary>
            public static readonly EntryId EvenPowerNeg = new("alg.exp.even-power-neg");

            /// <summary>Monotonicity of exponentials.</summary>
            public static readonly EntryId Monotone = new("alg.exp.monotone");

            /// <summary>Negative exponent.</summary>
            public static readonly EntryId Negative = new("alg.exp.negative");

            /// <summary>Odd power of a negative.</summary>
            public static readonly EntryId OddPowerNeg = new("alg.exp.odd-power-neg");

            /// <summary>Exponent one.</summary>
            public static readonly EntryId One = new("alg.exp.one");

            /// <summary>Base one.</summary>
            public static readonly EntryId OneBase = new("alg.exp.one-base");

            /// <summary>Equal powers, equal exponents.</summary>
            public static readonly EntryId OneToOne = new("alg.exp.one-to-one");

            /// <summary>Power of a power.</summary>
            public static readonly EntryId PowerOfPower = new("alg.exp.power-of-power");

            /// <summary>Power of a product.</summary>
            public static readonly EntryId PowerOfProduct = new("alg.exp.power-of-product");

            /// <summary>Power of a quotient.</summary>
            public static readonly EntryId PowerOfQuotient = new("alg.exp.power-of-quotient");

            /// <summary>Product of powers.</summary>
            public static readonly EntryId ProductOfPowers = new("alg.exp.product-of-powers");

            /// <summary>Quotient of powers.</summary>
            public static readonly EntryId QuotientOfPowers = new("alg.exp.quotient-of-powers");

            /// <summary>Rational exponent.</summary>
            public static readonly EntryId Rational = new("alg.exp.rational");

            /// <summary>Power as exponential.</summary>
            public static readonly EntryId ViaE = new("alg.exp.via-e");

            /// <summary>Zero exponent.</summary>
            public static readonly EntryId Zero = new("alg.exp.zero");

            /// <summary>Base zero.</summary>
            public static readonly EntryId ZeroBase = new("alg.exp.zero-base");
        }

        /// <summary>Fractions.</summary>
        public static class Frac
        {
            /// <summary>Add fractions.</summary>
            public static readonly EntryId Add = new("alg.frac.add");

            /// <summary>Add with a common denominator.</summary>
            public static readonly EntryId AddCommon = new("alg.frac.add-common");

            /// <summary>Cross multiplication.</summary>
            public static readonly EntryId CrossMult = new("alg.frac.cross-mult");

            /// <summary>Divide fractions.</summary>
            public static readonly EntryId Div = new("alg.frac.div");

            /// <summary>Equivalent fractions.</summary>
            public static readonly EntryId Equivalent = new("alg.frac.equivalent");

            /// <summary>Lowest terms.</summary>
            public static readonly EntryId LowestTerms = new("alg.frac.lowest-terms");

            /// <summary>Mixed number.</summary>
            public static readonly EntryId MixedNumber = new("alg.frac.mixed-number");

            /// <summary>Multiply fractions.</summary>
            public static readonly EntryId Mul = new("alg.frac.mul");

            /// <summary>Sign placement.</summary>
            public static readonly EntryId Neg = new("alg.frac.neg");

            /// <summary>Reciprocal of a fraction.</summary>
            public static readonly EntryId Reciprocal = new("alg.frac.reciprocal");
        }

        /// <summary>Logarithms.</summary>
        public static class Log
        {
            /// <summary>Change of base.</summary>
            public static readonly EntryId ChangeOfBase = new("alg.log.change-of-base");

            /// <summary>Complex logarithm of a product.</summary>
            public static readonly EntryId ComplexProduct = new("alg.log.complex-product");

            /// <summary>Logarithm of an even power.</summary>
            public static readonly EntryId EvenPower = new("alg.log.even-power");

            /// <summary>The exponential undoes the natural logarithm.</summary>
            public static readonly EntryId ExpLn = new("alg.log.exp-ln");

            /// <summary>Exponential undoes the logarithm.</summary>
            public static readonly EntryId InverseExp = new("alg.log.inverse-exp");

            /// <summary>Logarithm undoes the exponential.</summary>
            public static readonly EntryId InverseLog = new("alg.log.inverse-log");

            /// <summary>Natural logarithm of e.</summary>
            public static readonly EntryId LnE = new("alg.log.ln-e");

            /// <summary>Natural logarithm undoes the exponential.</summary>
            public static readonly EntryId LnExp = new("alg.log.ln-exp");

            /// <summary>Natural logarithm of a power.</summary>
            public static readonly EntryId LnPower = new("alg.log.ln-power");

            /// <summary>Natural logarithm of a product.</summary>
            public static readonly EntryId LnProduct = new("alg.log.ln-product");

            /// <summary>Natural logarithm of a quotient.</summary>
            public static readonly EntryId LnQuotient = new("alg.log.ln-quotient");

            /// <summary>Monotonicity of logarithms.</summary>
            public static readonly EntryId Monotone = new("alg.log.monotone");

            /// <summary>Natural logarithm.</summary>
            public static readonly EntryId Natural = new("alg.log.natural");

            /// <summary>Logarithm of the base.</summary>
            public static readonly EntryId OfBase = new("alg.log.of-base");

            /// <summary>Logarithm of one.</summary>
            public static readonly EntryId OfOne = new("alg.log.of-one");

            /// <summary>Logarithm is one-to-one.</summary>
            public static readonly EntryId OneToOne = new("alg.log.one-to-one");

            /// <summary>Logarithm of a power.</summary>
            public static readonly EntryId Power = new("alg.log.power");

            /// <summary>Logarithm with a power as base.</summary>
            public static readonly EntryId PowerBase = new("alg.log.power-base");

            /// <summary>Logarithm of a product.</summary>
            public static readonly EntryId Product = new("alg.log.product");

            /// <summary>Logarithm of a quotient.</summary>
            public static readonly EntryId Quotient = new("alg.log.quotient");

            /// <summary>Logarithm of a reciprocal.</summary>
            public static readonly EntryId Reciprocal = new("alg.log.reciprocal");

            /// <summary>Logarithm of a root.</summary>
            public static readonly EntryId Root = new("alg.log.root");

            /// <summary>Reciprocal bases.</summary>
            public static readonly EntryId Swap = new("alg.log.swap");
        }

        /// <summary>Order properties of the real numbers.</summary>
        public static class Order
        {
            /// <summary>Adding preserves order.</summary>
            public static readonly EntryId Add = new("alg.order.add");

            /// <summary>Multiplying by a negative reverses.</summary>
            public static readonly EntryId MulNeg = new("alg.order.mul-neg");

            /// <summary>Multiplying by a positive.</summary>
            public static readonly EntryId MulPos = new("alg.order.mul-pos");

            /// <summary>Reciprocals reverse order.</summary>
            public static readonly EntryId Reciprocal = new("alg.order.reciprocal");

            /// <summary>Squares are non-negative.</summary>
            public static readonly EntryId SquareNonneg = new("alg.order.square-nonneg");
        }

        /// <summary>Polynomials.</summary>
        public static class Poly
        {
            /// <summary>Binomial theorem.</summary>
            public static readonly EntryId BinomialTheorem = new("alg.poly.binomial-theorem");

            /// <summary>Cube of a difference.</summary>
            public static readonly EntryId CubeDiff = new("alg.poly.cube-diff");

            /// <summary>Cube of a sum.</summary>
            public static readonly EntryId CubeSum = new("alg.poly.cube-sum");

            /// <summary>Product of binomials (FOIL).</summary>
            public static readonly EntryId Foil = new("alg.poly.foil");

            /// <summary>Combine like terms.</summary>
            public static readonly EntryId LikeTerms = new("alg.poly.like-terms");

            /// <summary>Square of a difference.</summary>
            public static readonly EntryId SquareDiff = new("alg.poly.square-diff");

            /// <summary>Square of a sum.</summary>
            public static readonly EntryId SquareSum = new("alg.poly.square-sum");

            /// <summary>Square of a trinomial.</summary>
            public static readonly EntryId SquareTrinomial = new("alg.poly.square-trinomial");

            /// <summary>Sum times difference.</summary>
            public static readonly EntryId SumTimesDiff = new("alg.poly.sum-times-diff");
        }

        /// <summary>Consequences of the field axioms.</summary>
        public static class Prop
        {
            /// <summary>Division as multiplication.</summary>
            public static readonly EntryId DivDef = new("alg.prop.div-def");

            /// <summary>Double negation.</summary>
            public static readonly EntryId DoubleNeg = new("alg.prop.double-neg");

            /// <summary>Multiplication by zero.</summary>
            public static readonly EntryId MulZero = new("alg.prop.mul-zero");

            /// <summary>Multiplying by -1.</summary>
            public static readonly EntryId NegOne = new("alg.prop.neg-one");

            /// <summary>Signs of products.</summary>
            public static readonly EntryId NegProduct = new("alg.prop.neg-product");

            /// <summary>Opposite of a sum.</summary>
            public static readonly EntryId NegSum = new("alg.prop.neg-sum");

            /// <summary>Subtraction as addition.</summary>
            public static readonly EntryId SubDef = new("alg.prop.sub-def");

            /// <summary>Zero-product property.</summary>
            public static readonly EntryId ZeroProduct = new("alg.prop.zero-product");
        }

        /// <summary>Radicals.</summary>
        public static class Rad
        {
            /// <summary>Denesting square roots.</summary>
            public static readonly EntryId Denest = new("alg.rad.denest");

            /// <summary>Extract a square factor.</summary>
            public static readonly EntryId ExtractSquare = new("alg.rad.extract-square");

            /// <summary>Combine like radicals.</summary>
            public static readonly EntryId LikeRadicals = new("alg.rad.like-radicals");

            /// <summary>n-th root of a product.</summary>
            public static readonly EntryId NthProduct = new("alg.rad.nth-product");

            /// <summary>n-th root of a quotient.</summary>
            public static readonly EntryId NthQuotient = new("alg.rad.nth-quotient");

            /// <summary>Power of a root.</summary>
            public static readonly EntryId PowerOfRoot = new("alg.rad.power-of-root");

            /// <summary>Product rule for square roots.</summary>
            public static readonly EntryId Product = new("alg.rad.product");

            /// <summary>Quotient rule for square roots.</summary>
            public static readonly EntryId Quotient = new("alg.rad.quotient");

            /// <summary>Rationalize with a conjugate.</summary>
            public static readonly EntryId RationalizeConjugate = new("alg.rad.rationalize-conjugate");

            /// <summary>Rationalize a cube-root binomial.</summary>
            public static readonly EntryId RationalizeCube = new("alg.rad.rationalize-cube");

            /// <summary>Rationalize a monomial denominator.</summary>
            public static readonly EntryId RationalizeMonomial = new("alg.rad.rationalize-monomial");

            /// <summary>Even root of an even power.</summary>
            public static readonly EntryId RootOfPowerEven = new("alg.rad.root-of-power-even");

            /// <summary>Odd root of an odd power.</summary>
            public static readonly EntryId RootOfPowerOdd = new("alg.rad.root-of-power-odd");

            /// <summary>Root of a root.</summary>
            public static readonly EntryId RootOfRoot = new("alg.rad.root-of-root");

            /// <summary>Square root of a square.</summary>
            public static readonly EntryId SqrtOfSquare = new("alg.rad.sqrt-of-square");

            /// <summary>Square of a square root.</summary>
            public static readonly EntryId SquareOfSqrt = new("alg.rad.square-of-sqrt");
        }

        /// <summary>Rational expressions.</summary>
        public static class Rat
        {
            /// <summary>Cancel common factors.</summary>
            public static readonly EntryId Cancel = new("alg.rat.cancel");
        }

        /// <summary>Ratios and proportions.</summary>
        public static class Ratio
        {
            /// <summary>Proportion.</summary>
            public static readonly EntryId Proportion = new("alg.ratio.proportion");
        }
    }

    /// <summary>Calculus.</summary>
    public static class Calculus
    {
        /// <summary>Definite integrals.</summary>
        public static class Def
        {
            /// <summary>Reversing limits.</summary>
            public static readonly EntryId Reverse = new("calc.def.reverse");

            /// <summary>Zero-width interval.</summary>
            public static readonly EntryId ZeroWidth = new("calc.def.zero-width");
        }

        /// <summary>Derivative definition and rules.</summary>
        public static class Deriv
        {
            /// <summary>Chain rule.</summary>
            public static readonly EntryId Chain = new("calc.deriv.chain");

            /// <summary>Constant rule.</summary>
            public static readonly EntryId Constant = new("calc.deriv.constant");

            /// <summary>Constant multiple rule.</summary>
            public static readonly EntryId ConstantMultiple = new("calc.deriv.constant-multiple");

            /// <summary>General power rule.</summary>
            public static readonly EntryId GeneralPower = new("calc.deriv.general-power");

            /// <summary>General Leibniz rule.</summary>
            public static readonly EntryId Leibniz = new("calc.deriv.leibniz");

            /// <summary>Power rule.</summary>
            public static readonly EntryId Power = new("calc.deriv.power");

            /// <summary>Product rule.</summary>
            public static readonly EntryId Product = new("calc.deriv.product");

            /// <summary>Quotient rule.</summary>
            public static readonly EntryId Quotient = new("calc.deriv.quotient");

            /// <summary>Reciprocal rule.</summary>
            public static readonly EntryId Reciprocal = new("calc.deriv.reciprocal");

            /// <summary>Sum rule.</summary>
            public static readonly EntryId Sum = new("calc.deriv.sum");

            /// <summary>Variable base and exponent.</summary>
            public static readonly EntryId VarPower = new("calc.deriv.var-power");
        }

        /// <summary>Derivative table.</summary>
        public static class Dtab
        {
            /// <summary>Derivative of the absolute value.</summary>
            public static readonly EntryId Abs = new("calc.dtab.abs");

            /// <summary>Derivative of arccosine.</summary>
            public static readonly EntryId Arccos = new("calc.dtab.arccos");

            /// <summary>Derivative of arccotangent.</summary>
            public static readonly EntryId Arccot = new("calc.dtab.arccot");

            /// <summary>Derivative of arccosecant.</summary>
            public static readonly EntryId Arccsc = new("calc.dtab.arccsc");

            /// <summary>Derivative of inverse hyperbolic cosine.</summary>
            public static readonly EntryId Arcosh = new("calc.dtab.arcosh");

            /// <summary>Derivative of arcsecant.</summary>
            public static readonly EntryId Arcsec = new("calc.dtab.arcsec");

            /// <summary>Derivative of arcsine.</summary>
            public static readonly EntryId Arcsin = new("calc.dtab.arcsin");

            /// <summary>Derivative of arctangent.</summary>
            public static readonly EntryId Arctan = new("calc.dtab.arctan");

            /// <summary>Derivative of inverse hyperbolic sine.</summary>
            public static readonly EntryId Arsinh = new("calc.dtab.arsinh");

            /// <summary>Derivative of inverse hyperbolic tangent.</summary>
            public static readonly EntryId Artanh = new("calc.dtab.artanh");

            /// <summary>Derivative of cosine.</summary>
            public static readonly EntryId Cos = new("calc.dtab.cos");

            /// <summary>Derivative of hyperbolic cosine.</summary>
            public static readonly EntryId Cosh = new("calc.dtab.cosh");

            /// <summary>Derivative of cotangent.</summary>
            public static readonly EntryId Cot = new("calc.dtab.cot");

            /// <summary>Derivative of hyperbolic cotangent.</summary>
            public static readonly EntryId Coth = new("calc.dtab.coth");

            /// <summary>Derivative of cosecant.</summary>
            public static readonly EntryId Csc = new("calc.dtab.csc");

            /// <summary>Derivative of hyperbolic cosecant.</summary>
            public static readonly EntryId Csch = new("calc.dtab.csch");

            /// <summary>Derivative of the error function.</summary>
            public static readonly EntryId Erf = new("calc.dtab.erf");

            /// <summary>Derivative of e^x.</summary>
            public static readonly EntryId Exp = new("calc.dtab.exp");

            /// <summary>Derivative of a^x.</summary>
            public static readonly EntryId ExpBase = new("calc.dtab.exp-base");

            /// <summary>Derivative of the gamma function.</summary>
            public static readonly EntryId Gamma = new("calc.dtab.gamma");

            /// <summary>Derivative of the Lambert W function.</summary>
            public static readonly EntryId Lambertw = new("calc.dtab.lambertw");

            /// <summary>Derivative of ln x.</summary>
            public static readonly EntryId Ln = new("calc.dtab.ln");

            /// <summary>Derivative of ln |x|.</summary>
            public static readonly EntryId LnAbs = new("calc.dtab.ln-abs");

            /// <summary>Derivative of log base a.</summary>
            public static readonly EntryId LogBase = new("calc.dtab.log-base");

            /// <summary>Derivative of secant.</summary>
            public static readonly EntryId Sec = new("calc.dtab.sec");

            /// <summary>Derivative of hyperbolic secant.</summary>
            public static readonly EntryId Sech = new("calc.dtab.sech");

            /// <summary>Derivative of sine.</summary>
            public static readonly EntryId Sin = new("calc.dtab.sin");

            /// <summary>Derivative of hyperbolic sine.</summary>
            public static readonly EntryId Sinh = new("calc.dtab.sinh");

            /// <summary>Derivative of the square root.</summary>
            public static readonly EntryId Sqrt = new("calc.dtab.sqrt");

            /// <summary>Derivative of tangent.</summary>
            public static readonly EntryId Tan = new("calc.dtab.tan");

            /// <summary>Derivative of hyperbolic tangent.</summary>
            public static readonly EntryId Tanh = new("calc.dtab.tanh");
        }

        /// <summary>Integration techniques.</summary>
        public static class Int
        {
            /// <summary>Linearity of the integral.</summary>
            public static readonly EntryId Linearity = new("calc.int.linearity");

            /// <summary>Integration by parts.</summary>
            public static readonly EntryId Parts = new("calc.int.parts");

            /// <summary>Definite integration by parts.</summary>
            public static readonly EntryId PartsDefinite = new("calc.int.parts-definite");

            /// <summary>Substitution.</summary>
            public static readonly EntryId Substitution = new("calc.int.substitution");

            /// <summary>Definite substitution.</summary>
            public static readonly EntryId SubstitutionDefinite = new("calc.int.substitution-definite");
        }

        /// <summary>Table of antiderivatives.</summary>
        public static class Itab
        {
            /// <summary>Antiderivative leading to inverse hyperbolic cosine.</summary>
            public static readonly EntryId ArcoshForm = new("calc.itab.arcosh-form");

            /// <summary>Antiderivative leading to arcsecant.</summary>
            public static readonly EntryId ArcsecForm = new("calc.itab.arcsec-form");

            /// <summary>Antiderivative leading to arcsine.</summary>
            public static readonly EntryId ArcsinForm = new("calc.itab.arcsin-form");

            /// <summary>Antiderivative leading to arctangent.</summary>
            public static readonly EntryId ArctanForm = new("calc.itab.arctan-form");

            /// <summary>Antiderivative leading to inverse hyperbolic sine.</summary>
            public static readonly EntryId ArsinhForm = new("calc.itab.arsinh-form");

            /// <summary>Antiderivative of cosine.</summary>
            public static readonly EntryId Cos = new("calc.itab.cos");

            /// <summary>Antiderivative of cos².</summary>
            public static readonly EntryId CosSq = new("calc.itab.cos-sq");

            /// <summary>Antiderivative of hyperbolic cosine.</summary>
            public static readonly EntryId Cosh = new("calc.itab.cosh");

            /// <summary>Antiderivative of cotangent.</summary>
            public static readonly EntryId Cot = new("calc.itab.cot");

            /// <summary>Antiderivative of cosecant.</summary>
            public static readonly EntryId Csc = new("calc.itab.csc");

            /// <summary>Antiderivative of csc·cot.</summary>
            public static readonly EntryId CscCot = new("calc.itab.csc-cot");

            /// <summary>Antiderivative of csc².</summary>
            public static readonly EntryId CscSq = new("calc.itab.csc-sq");

            /// <summary>Antiderivative of e^x.</summary>
            public static readonly EntryId Exp = new("calc.itab.exp");

            /// <summary>Antiderivative of a^x.</summary>
            public static readonly EntryId ExpBase = new("calc.itab.exp-base");

            /// <summary>Antiderivative of e^(ax) cos(bx).</summary>
            public static readonly EntryId ExpCos = new("calc.itab.exp-cos");

            /// <summary>Antiderivative of e^(ax).</summary>
            public static readonly EntryId ExpLinear = new("calc.itab.exp-linear");

            /// <summary>Antiderivative of e^(ax) sin(bx).</summary>
            public static readonly EntryId ExpSin = new("calc.itab.exp-sin");

            /// <summary>Antiderivative of e^(−x²).</summary>
            public static readonly EntryId Gaussian = new("calc.itab.gaussian");

            /// <summary>Antiderivative of 1/ln x.</summary>
            public static readonly EntryId InvLog = new("calc.itab.inv-log");

            /// <summary>Antiderivative of ln x.</summary>
            public static readonly EntryId Ln = new("calc.itab.ln");

            /// <summary>Antiderivative of 1/(x² − a²).</summary>
            public static readonly EntryId LogDiffSquares = new("calc.itab.log-diff-squares");

            /// <summary>Antiderivative of a power.</summary>
            public static readonly EntryId Power = new("calc.itab.power");

            /// <summary>Antiderivative of 1/x.</summary>
            public static readonly EntryId Reciprocal = new("calc.itab.reciprocal");

            /// <summary>Antiderivative of secant.</summary>
            public static readonly EntryId Sec = new("calc.itab.sec");

            /// <summary>Antiderivative of sec².</summary>
            public static readonly EntryId SecSq = new("calc.itab.sec-sq");

            /// <summary>Antiderivative of sec·tan.</summary>
            public static readonly EntryId SecTan = new("calc.itab.sec-tan");

            /// <summary>Antiderivative of sqrt(a² − x²).</summary>
            public static readonly EntryId Semicircle = new("calc.itab.semicircle");

            /// <summary>Antiderivative of sine.</summary>
            public static readonly EntryId Sin = new("calc.itab.sin");

            /// <summary>Antiderivative of sin².</summary>
            public static readonly EntryId SinSq = new("calc.itab.sin-sq");

            /// <summary>Antiderivative of sin(x)/x.</summary>
            public static readonly EntryId Sinc = new("calc.itab.sinc");

            /// <summary>Antiderivative of hyperbolic sine.</summary>
            public static readonly EntryId Sinh = new("calc.itab.sinh");

            /// <summary>Antiderivative of tangent.</summary>
            public static readonly EntryId Tan = new("calc.itab.tan");

            /// <summary>Antiderivative of x e^x.</summary>
            public static readonly EntryId XExp = new("calc.itab.x-exp");
        }

        /// <summary>Limits.</summary>
        public static class Lim
        {
            /// <summary>Arctangent at infinity.</summary>
            public static readonly EntryId ArctanInfinity = new("calc.lim.arctan-infinity");

            /// <summary>Constant multiple law for limits.</summary>
            public static readonly EntryId ConstantMultiple = new("calc.lim.constant-multiple");

            /// <summary>Compound growth limit.</summary>
            public static readonly EntryId EGeneral = new("calc.lim.e-general");

            /// <summary>Definition of e as a limit.</summary>
            public static readonly EntryId ESequence = new("calc.lim.e-sequence");

            /// <summary>e as a limit at 0.</summary>
            public static readonly EntryId EZero = new("calc.lim.e-zero");

            /// <summary>Exponential limit.</summary>
            public static readonly EntryId ExpMinusOne = new("calc.lim.exp-minus-one");

            /// <summary>Powers of a fraction.</summary>
            public static readonly EntryId Geometric = new("calc.lim.geometric");

            /// <summary>Logarithm limit.</summary>
            public static readonly EntryId LogOnePlus = new("calc.lim.log-one-plus");

            /// <summary>n-th root of n.</summary>
            public static readonly EntryId NthRootN = new("calc.lim.nth-root-n");

            /// <summary>Cosine limit.</summary>
            public static readonly EntryId OneMinusCosOverX = new("calc.lim.one-minus-cos-over-x");

            /// <summary>Cosine limit (second order).</summary>
            public static readonly EntryId OneMinusCosOverX2 = new("calc.lim.one-minus-cos-over-x2");

            /// <summary>Power law for limits.</summary>
            public static readonly EntryId Power = new("calc.lim.power");

            /// <summary>General exponential limit.</summary>
            public static readonly EntryId PowerMinusOne = new("calc.lim.power-minus-one");

            /// <summary>Product law for limits.</summary>
            public static readonly EntryId Product = new("calc.lim.product");

            /// <summary>Quotient law for limits.</summary>
            public static readonly EntryId Quotient = new("calc.lim.quotient");

            /// <summary>Root law for limits.</summary>
            public static readonly EntryId Root = new("calc.lim.root");

            /// <summary>Fundamental trigonometric limit.</summary>
            public static readonly EntryId SinOverX = new("calc.lim.sin-over-x");

            /// <summary>Sum law for limits.</summary>
            public static readonly EntryId Sum = new("calc.lim.sum");

            /// <summary>Tangent limit.</summary>
            public static readonly EntryId TanOverX = new("calc.lim.tan-over-x");

            /// <summary>x ln x at 0.</summary>
            public static readonly EntryId XLnX = new("calc.lim.x-ln-x");

            /// <summary>x to the x at 0.</summary>
            public static readonly EntryId XToX = new("calc.lim.x-to-x");
        }

        /// <summary>Maclaurin series.</summary>
        public static class Mac
        {
            /// <summary>Maclaurin series of arctan.</summary>
            public static readonly EntryId Arctan = new("calc.mac.arctan");

            /// <summary>Binomial series.</summary>
            public static readonly EntryId Binomial = new("calc.mac.binomial");

            /// <summary>Maclaurin series of cos.</summary>
            public static readonly EntryId Cos = new("calc.mac.cos");

            /// <summary>Maclaurin series of cosh.</summary>
            public static readonly EntryId Cosh = new("calc.mac.cosh");

            /// <summary>Maclaurin series of eˣ.</summary>
            public static readonly EntryId Exp = new("calc.mac.exp");

            /// <summary>Geometric series.</summary>
            public static readonly EntryId Geometric = new("calc.mac.geometric");

            /// <summary>Maclaurin series of ln(1 + x).</summary>
            public static readonly EntryId Ln = new("calc.mac.ln");

            /// <summary>Maclaurin series of sin.</summary>
            public static readonly EntryId Sin = new("calc.mac.sin");

            /// <summary>Maclaurin series of sinh.</summary>
            public static readonly EntryId Sinh = new("calc.mac.sinh");
        }
    }

    /// <summary>LinearAlgebra.</summary>
    public static class LinearAlgebra
    {
        /// <summary>Determinants.</summary>
        public static class Det
        {
            /// <summary>Block triangular determinant.</summary>
            public static readonly EntryId BlockTriangular = new("linalg.det.block-triangular");

            /// <summary>Determinant of the inverse.</summary>
            public static readonly EntryId Inverse = new("linalg.det.inverse");

            /// <summary>Matrix determinant lemma.</summary>
            public static readonly EntryId MatrixDeterminantLemma = new("linalg.det.matrix-determinant-lemma");

            /// <summary>Multiplicativity of the determinant.</summary>
            public static readonly EntryId Product = new("linalg.det.product");

            /// <summary>Determinant of a scalar multiple.</summary>
            public static readonly EntryId Scalar = new("linalg.det.scalar");

            /// <summary>Sylvester's determinant identity.</summary>
            public static readonly EntryId Sylvester = new("linalg.det.sylvester");

            /// <summary>Determinant of the transpose.</summary>
            public static readonly EntryId Transpose = new("linalg.det.transpose");
        }
    }

    /// <summary>Trigonometry.</summary>
    public static class Trigonometry
    {
        /// <summary>Exact values of sine, cosine and tangent.</summary>
        public static class Exact
        {
            /// <summary>Exact values at 2π/5 (72°).</summary>
            public static readonly EntryId _2pi5 = new("trig.exact.2pi-5");

            /// <summary>Exact values at 3π/10 (54°).</summary>
            public static readonly EntryId _3pi10 = new("trig.exact.3pi-10");

            /// <summary>Exact values at 3π/8 (67.5°).</summary>
            public static readonly EntryId _3pi8 = new("trig.exact.3pi-8");

            /// <summary>Exact values at 5π/12 (75°).</summary>
            public static readonly EntryId _5pi12 = new("trig.exact.5pi-12");

            /// <summary>Exact values at π/10 (18°).</summary>
            public static readonly EntryId Pi10 = new("trig.exact.pi-10");

            /// <summary>Exact values at π/12 (15°).</summary>
            public static readonly EntryId Pi12 = new("trig.exact.pi-12");

            /// <summary>Exact values at π/2 (90°).</summary>
            public static readonly EntryId Pi2 = new("trig.exact.pi-2");

            /// <summary>Exact values at π/3 (60°).</summary>
            public static readonly EntryId Pi3 = new("trig.exact.pi-3");

            /// <summary>Exact values at π/4 (45°).</summary>
            public static readonly EntryId Pi4 = new("trig.exact.pi-4");

            /// <summary>Exact values at π/5 (36°).</summary>
            public static readonly EntryId Pi5 = new("trig.exact.pi-5");

            /// <summary>Exact values at π/6 (30°).</summary>
            public static readonly EntryId Pi6 = new("trig.exact.pi-6");

            /// <summary>Exact values at π/8 (22.5°).</summary>
            public static readonly EntryId Pi8 = new("trig.exact.pi-8");

            /// <summary>Exact values at 0.</summary>
            public static readonly EntryId Zero = new("trig.exact.zero");
        }

        /// <summary>Exponential forms.</summary>
        public static class Exp
        {
            /// <summary>Cosine as exponentials.</summary>
            public static readonly EntryId Cos = new("trig.exp.cos");

            /// <summary>Euler's formula.</summary>
            public static readonly EntryId Euler = new("trig.exp.euler");

            /// <summary>Euler's identity.</summary>
            public static readonly EntryId EulerIdentity = new("trig.exp.euler-identity");

            /// <summary>Sine as exponentials.</summary>
            public static readonly EntryId Sin = new("trig.exp.sin");

            /// <summary>Tangent as exponentials.</summary>
            public static readonly EntryId Tan = new("trig.exp.tan");
        }

        /// <summary>Half angles.</summary>
        public static class Half
        {
            /// <summary>Half angle (cosine).</summary>
            public static readonly EntryId Cos = new("trig.half.cos");

            /// <summary>Half angle (sine).</summary>
            public static readonly EntryId Sin = new("trig.half.sin");

            /// <summary>Half angle (tangent, alternate form).</summary>
            public static readonly EntryId TanCos = new("trig.half.tan-cos");

            /// <summary>Half angle (tangent).</summary>
            public static readonly EntryId TanSin = new("trig.half.tan-sin");
        }

        /// <summary>Fundamental identities.</summary>
        public static class Id
        {
            /// <summary>Cofunction identity (cosine).</summary>
            public static readonly EntryId CofunctionCos = new("trig.id.cofunction-cos");

            /// <summary>Cofunction identity (secant).</summary>
            public static readonly EntryId CofunctionSec = new("trig.id.cofunction-sec");

            /// <summary>Cofunction identity (sine).</summary>
            public static readonly EntryId CofunctionSin = new("trig.id.cofunction-sin");

            /// <summary>Cofunction identity (tangent).</summary>
            public static readonly EntryId CofunctionTan = new("trig.id.cofunction-tan");

            /// <summary>Cosine is even.</summary>
            public static readonly EntryId CosEven = new("trig.id.cos-even");

            /// <summary>Cotangent is odd.</summary>
            public static readonly EntryId CotOdd = new("trig.id.cot-odd");

            /// <summary>Cosecant is odd.</summary>
            public static readonly EntryId CscOdd = new("trig.id.csc-odd");

            /// <summary>Periods of sine, cosine, secant and cosecant.</summary>
            public static readonly EntryId PeriodSin = new("trig.id.period-sin");

            /// <summary>Periods of tangent and cotangent.</summary>
            public static readonly EntryId PeriodTan = new("trig.id.period-tan");

            /// <summary>Pythagorean identity.</summary>
            public static readonly EntryId Pythagorean = new("trig.id.pythagorean");

            /// <summary>Pythagorean identity (cot).</summary>
            public static readonly EntryId PythagoreanCot = new("trig.id.pythagorean-cot");

            /// <summary>Pythagorean identity (tan).</summary>
            public static readonly EntryId PythagoreanTan = new("trig.id.pythagorean-tan");

            /// <summary>Secant is even.</summary>
            public static readonly EntryId SecEven = new("trig.id.sec-even");

            /// <summary>Quarter-turn (cosine).</summary>
            public static readonly EntryId ShiftHalfPiCos = new("trig.id.shift-half-pi-cos");

            /// <summary>Quarter-turn (sine).</summary>
            public static readonly EntryId ShiftHalfPiSin = new("trig.id.shift-half-pi-sin");

            /// <summary>Half-turn (cosine).</summary>
            public static readonly EntryId ShiftPiCos = new("trig.id.shift-pi-cos");

            /// <summary>Half-turn (sine).</summary>
            public static readonly EntryId ShiftPiSin = new("trig.id.shift-pi-sin");

            /// <summary>Sine is odd.</summary>
            public static readonly EntryId SinOdd = new("trig.id.sin-odd");

            /// <summary>Supplementary angle (cosine).</summary>
            public static readonly EntryId SupplementCos = new("trig.id.supplement-cos");

            /// <summary>Supplementary angle (sine).</summary>
            public static readonly EntryId SupplementSin = new("trig.id.supplement-sin");

            /// <summary>Tangent is odd.</summary>
            public static readonly EntryId TanOdd = new("trig.id.tan-odd");
        }

        /// <summary>Inverse trigonometric functions.</summary>
        public static class Inv
        {
            /// <summary>Arccosine of cosine.</summary>
            public static readonly EntryId ArccosCos = new("trig.inv.arccos-cos");

            /// <summary>Arccosine of a negative.</summary>
            public static readonly EntryId ArccosNeg = new("trig.inv.arccos-neg");

            /// <summary>Arccosecant.</summary>
            public static readonly EntryId ArccscDef = new("trig.inv.arccsc-def");

            /// <summary>Arcsecant.</summary>
            public static readonly EntryId ArcsecDef = new("trig.inv.arcsec-def");

            /// <summary>Arcsine is odd.</summary>
            public static readonly EntryId ArcsinOdd = new("trig.inv.arcsin-odd");

            /// <summary>Complementary inverses (arcsin and arccos).</summary>
            public static readonly EntryId ArcsinPlusArccos = new("trig.inv.arcsin-plus-arccos");

            /// <summary>Arcsine of sine.</summary>
            public static readonly EntryId ArcsinSin = new("trig.inv.arcsin-sin");

            /// <summary>Arctangent is odd.</summary>
            public static readonly EntryId ArctanOdd = new("trig.inv.arctan-odd");

            /// <summary>Complementary inverses (arctan and arccot).</summary>
            public static readonly EntryId ArctanPlusArccot = new("trig.inv.arctan-plus-arccot");

            /// <summary>Arctangent of a reciprocal.</summary>
            public static readonly EntryId ArctanReciprocal = new("trig.inv.arctan-reciprocal");

            /// <summary>Arctangent addition.</summary>
            public static readonly EntryId ArctanSum = new("trig.inv.arctan-sum");

            /// <summary>Arctangent of tangent.</summary>
            public static readonly EntryId ArctanTan = new("trig.inv.arctan-tan");

            /// <summary>Cosine of arccosine.</summary>
            public static readonly EntryId CosArccos = new("trig.inv.cos-arccos");

            /// <summary>Cosine of arcsine.</summary>
            public static readonly EntryId CosArcsin = new("trig.inv.cos-arcsin");

            /// <summary>Cosine of arctangent.</summary>
            public static readonly EntryId CosArctan = new("trig.inv.cos-arctan");

            /// <summary>Sine of arccosine.</summary>
            public static readonly EntryId SinArccos = new("trig.inv.sin-arccos");

            /// <summary>Sine of arcsine.</summary>
            public static readonly EntryId SinArcsin = new("trig.inv.sin-arcsin");

            /// <summary>Sine of arctangent.</summary>
            public static readonly EntryId SinArctan = new("trig.inv.sin-arctan");

            /// <summary>Tangent of arccosine.</summary>
            public static readonly EntryId TanArccos = new("trig.inv.tan-arccos");

            /// <summary>Tangent of arcsine.</summary>
            public static readonly EntryId TanArcsin = new("trig.inv.tan-arcsin");

            /// <summary>Tangent of arctangent.</summary>
            public static readonly EntryId TanArctan = new("trig.inv.tan-arctan");
        }

        /// <summary>Linear combinations of sine and cosine.</summary>
        public static class Lin
        {
            /// <summary>Harmonic addition (cosine form).</summary>
            public static readonly EntryId CosForm = new("trig.lin.cos-form");

            /// <summary>Harmonic addition (sine form).</summary>
            public static readonly EntryId SinForm = new("trig.lin.sin-form");
        }

        /// <summary>Multiple angles.</summary>
        public static class Mult
        {
            /// <summary>Cosine of a multiple.</summary>
            public static readonly EntryId Chebyshev = new("trig.mult.chebyshev");

            /// <summary>Double angle (cosine).</summary>
            public static readonly EntryId CosDouble = new("trig.mult.cos-double");

            /// <summary>Double angle (cosine, cosine form).</summary>
            public static readonly EntryId CosDoubleCos = new("trig.mult.cos-double-cos");

            /// <summary>Double angle (cosine, sine form).</summary>
            public static readonly EntryId CosDoubleSin = new("trig.mult.cos-double-sin");

            /// <summary>Triple angle (cosine).</summary>
            public static readonly EntryId CosTriple = new("trig.mult.cos-triple");

            /// <summary>Multiple angles from De Moivre.</summary>
            public static readonly EntryId DeMoivre = new("trig.mult.de-moivre");

            /// <summary>Double angle (sine).</summary>
            public static readonly EntryId SinDouble = new("trig.mult.sin-double");

            /// <summary>Triple angle (sine).</summary>
            public static readonly EntryId SinTriple = new("trig.mult.sin-triple");

            /// <summary>Double angle (tangent).</summary>
            public static readonly EntryId TanDouble = new("trig.mult.tan-double");

            /// <summary>Triple angle (tangent).</summary>
            public static readonly EntryId TanTriple = new("trig.mult.tan-triple");
        }

        /// <summary>Power reduction.</summary>
        public static class Power
        {
            /// <summary>Power reduction (cos³).</summary>
            public static readonly EntryId CosCube = new("trig.power.cos-cube");

            /// <summary>Power reduction (cos⁴).</summary>
            public static readonly EntryId CosFourth = new("trig.power.cos-fourth");

            /// <summary>Power reduction (cos²).</summary>
            public static readonly EntryId CosSq = new("trig.power.cos-sq");

            /// <summary>Power reduction (sin³).</summary>
            public static readonly EntryId SinCube = new("trig.power.sin-cube");

            /// <summary>Power reduction (sin⁴).</summary>
            public static readonly EntryId SinFourth = new("trig.power.sin-fourth");

            /// <summary>Power reduction (sin²).</summary>
            public static readonly EntryId SinSq = new("trig.power.sin-sq");

            /// <summary>Product of squares.</summary>
            public static readonly EntryId SinSqCosSq = new("trig.power.sin-sq-cos-sq");

            /// <summary>Power reduction (tan²).</summary>
            public static readonly EntryId TanSq = new("trig.power.tan-sq");
        }

        /// <summary>Product to sum.</summary>
        public static class Prod
        {
            /// <summary>Product of cosines.</summary>
            public static readonly EntryId CosCos = new("trig.prod.cos-cos");

            /// <summary>Cosine times sine.</summary>
            public static readonly EntryId CosSin = new("trig.prod.cos-sin");

            /// <summary>Sine times cosine.</summary>
            public static readonly EntryId SinCos = new("trig.prod.sin-cos");

            /// <summary>Product of sines.</summary>
            public static readonly EntryId SinSin = new("trig.prod.sin-sin");
        }

        /// <summary>Sum to product.</summary>
        public static class S2p
        {
            /// <summary>Difference of cosines.</summary>
            public static readonly EntryId CosMinusCos = new("trig.s2p.cos-minus-cos");

            /// <summary>Sum of cosines.</summary>
            public static readonly EntryId CosPlusCos = new("trig.s2p.cos-plus-cos");

            /// <summary>Difference of sines.</summary>
            public static readonly EntryId SinMinusSin = new("trig.s2p.sin-minus-sin");

            /// <summary>Sum of sines.</summary>
            public static readonly EntryId SinPlusSin = new("trig.s2p.sin-plus-sin");
        }

        /// <summary>Sum and difference.</summary>
        public static class Sum
        {
            /// <summary>Cosine of a difference.</summary>
            public static readonly EntryId CosOfDiff = new("trig.sum.cos-of-diff");

            /// <summary>Cosine of a sum.</summary>
            public static readonly EntryId CosOfSum = new("trig.sum.cos-of-sum");

            /// <summary>Sine of a difference.</summary>
            public static readonly EntryId SinOfDiff = new("trig.sum.sin-of-diff");

            /// <summary>Sine of a sum.</summary>
            public static readonly EntryId SinOfSum = new("trig.sum.sin-of-sum");

            /// <summary>Tangent of a difference.</summary>
            public static readonly EntryId TanOfDiff = new("trig.sum.tan-of-diff");

            /// <summary>Tangent of a sum.</summary>
            public static readonly EntryId TanOfSum = new("trig.sum.tan-of-sum");
        }

        /// <summary>Weierstrass substitution.</summary>
        public static class Weier
        {
            /// <summary>Weierstrass substitution (cosine).</summary>
            public static readonly EntryId Cos = new("trig.weier.cos");

            /// <summary>Weierstrass substitution (sine).</summary>
            public static readonly EntryId Sin = new("trig.weier.sin");

            /// <summary>Weierstrass substitution (tangent).</summary>
            public static readonly EntryId Tan = new("trig.weier.tan");
        }
    }
}

/// <summary>Handles of the catalog entries of kind theorem.</summary>
public static class Theorems
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Equations.</summary>
        public static class Eq
        {
            /// <summary>Dividing by an expression that can vanish may lose solutions.</summary>
            public static readonly EntryId DivideByVariable = new("alg.eq.divide-by-variable");

            /// <summary>Adding preserves solutions.</summary>
            public static readonly EntryId EquivAdd = new("alg.eq.equiv-add");

            /// <summary>Applying a one-to-one function preserves solutions.</summary>
            public static readonly EntryId EquivInjective = new("alg.eq.equiv-injective");

            /// <summary>Multiplying by a non-zero quantity preserves solutions.</summary>
            public static readonly EntryId EquivMul = new("alg.eq.equiv-mul");

            /// <summary>Multiplying by an expression that can vanish may add solutions.</summary>
            public static readonly EntryId MulByVariable = new("alg.eq.mul-by-variable");

            /// <summary>Squaring may add solutions.</summary>
            public static readonly EntryId SquareBothSides = new("alg.eq.square-both-sides");
        }

        /// <summary>Factoring.</summary>
        public static class Factor
        {
            /// <summary>Factor from roots.</summary>
            public static readonly EntryId ByRoots = new("alg.factor.by-roots");
        }

        /// <summary>Inequalities.</summary>
        public static class Ineq
        {
            /// <summary>Compound inequality.</summary>
            public static readonly EntryId Compound = new("alg.ineq.compound");
        }

        /// <summary>Partial fractions.</summary>
        public static class Pf
        {
            /// <summary>Uniqueness of partial fractions.</summary>
            public static readonly EntryId Uniqueness = new("alg.pf.uniqueness");
        }

        /// <summary>Polynomials.</summary>
        public static class Poly
        {
            /// <summary>Upper and lower bound theorem.</summary>
            public static readonly EntryId BoundTheorem = new("alg.poly.bound-theorem");

            /// <summary>Cauchy root bound.</summary>
            public static readonly EntryId CauchyBound = new("alg.poly.cauchy-bound");

            /// <summary>Complex conjugate roots.</summary>
            public static readonly EntryId ConjugateRoots = new("alg.poly.conjugate-roots");

            /// <summary>Degree of a product.</summary>
            public static readonly EntryId DegreeProduct = new("alg.poly.degree-product");

            /// <summary>Degree of a sum.</summary>
            public static readonly EntryId DegreeSum = new("alg.poly.degree-sum");

            /// <summary>Descartes' rule of signs.</summary>
            public static readonly EntryId Descartes = new("alg.poly.descartes");

            /// <summary>Division algorithm.</summary>
            public static readonly EntryId DivisionAlgorithm = new("alg.poly.division-algorithm");

            /// <summary>Factor theorem.</summary>
            public static readonly EntryId FactorTheorem = new("alg.poly.factor-theorem");

            /// <summary>Fundamental Theorem of Algebra.</summary>
            public static readonly EntryId Fta = new("alg.poly.fta");

            /// <summary>Irrational conjugate roots.</summary>
            public static readonly EntryId IrrationalConjugates = new("alg.poly.irrational-conjugates");

            /// <summary>Sign change implies a root.</summary>
            public static readonly EntryId Ivt = new("alg.poly.ivt");

            /// <summary>LCM via GCD.</summary>
            public static readonly EntryId Lcm = new("alg.poly.lcm");

            /// <summary>Multinomial theorem.</summary>
            public static readonly EntryId MultinomialTheorem = new("alg.poly.multinomial-theorem");

            /// <summary>Rational Root Theorem.</summary>
            public static readonly EntryId RationalRoot = new("alg.poly.rational-root");

            /// <summary>Remainder theorem.</summary>
            public static readonly EntryId RemainderTheorem = new("alg.poly.remainder-theorem");

            /// <summary>Vieta's formulas.</summary>
            public static readonly EntryId Vieta = new("alg.poly.vieta");
        }

        /// <summary>Quadratics.</summary>
        public static class Quad
        {
            /// <summary>The vertex is the extremum.</summary>
            public static readonly EntryId Extremum = new("alg.quad.extremum");

            /// <summary>Nature of the roots.</summary>
            public static readonly EntryId RootNature = new("alg.quad.root-nature");

            /// <summary>Sum and product of the roots.</summary>
            public static readonly EntryId Vieta = new("alg.quad.vieta");
        }

        /// <summary>Systems of equations.</summary>
        public static class Sys
        {
            /// <summary>Linear systems: one solution, none, or infinitely many.</summary>
            public static readonly EntryId Classification = new("alg.sys.classification");
        }
    }

    /// <summary>Calculus.</summary>
    public static class Calculus
    {
        /// <summary>Derivative definition and rules.</summary>
        public static class Deriv
        {
            /// <summary>Derivative of an inverse function.</summary>
            public static readonly EntryId InverseFunction = new("calc.deriv.inverse-function");
        }

        /// <summary>Fundamental Theorem of Calculus.</summary>
        public static class Ftc
        {
            /// <summary>Fundamental Theorem of Calculus, part 2.</summary>
            public static readonly EntryId Part2 = new("calc.ftc.part2");
        }

        /// <summary>Integration techniques.</summary>
        public static class Int
        {
            /// <summary>Liouville's theorem on elementary integrability.</summary>
            public static readonly EntryId Liouville = new("calc.int.liouville");

            /// <summary>Rational functions have elementary antiderivatives.</summary>
            public static readonly EntryId RationalComplete = new("calc.int.rational-complete");
        }

        /// <summary>Limits.</summary>
        public static class Lim
        {
            /// <summary>Limit of a composition.</summary>
            public static readonly EntryId Composition = new("calc.lim.composition");

            /// <summary>Direct substitution.</summary>
            public static readonly EntryId DirectSubstitution = new("calc.lim.direct-substitution");

            /// <summary>Growth hierarchy.</summary>
            public static readonly EntryId GrowthHierarchy = new("calc.lim.growth-hierarchy");

            /// <summary>L'Hôpital's rule.</summary>
            public static readonly EntryId Lhopital = new("calc.lim.lhopital");

            /// <summary>Two-sided limit from one-sided limits.</summary>
            public static readonly EntryId OneSided = new("calc.lim.one-sided");

            /// <summary>Rational functions at infinity.</summary>
            public static readonly EntryId RationalAtInfinity = new("calc.lim.rational-at-infinity");

            /// <summary>Squeeze theorem.</summary>
            public static readonly EntryId Squeeze = new("calc.lim.squeeze");
        }

        /// <summary>Taylor series.</summary>
        public static class Series
        {
            /// <summary>Taylor's inequality.</summary>
            public static readonly EntryId TaylorInequality = new("calc.series.taylor-inequality");

            /// <summary>Taylor's theorem (Lagrange remainder).</summary>
            public static readonly EntryId TaylorRemainder = new("calc.series.taylor-remainder");
        }
    }

    /// <summary>LinearAlgebra.</summary>
    public static class LinearAlgebra
    {
        /// <summary>Determinants.</summary>
        public static class Det
        {
            /// <summary>Adjugate formula.</summary>
            public static readonly EntryId Adjugate = new("linalg.det.adjugate");

            /// <summary>Cofactor (Laplace) expansion.</summary>
            public static readonly EntryId Cofactor = new("linalg.det.cofactor");

            /// <summary>Determinant and eigenvalues.</summary>
            public static readonly EntryId Eigen = new("linalg.det.eigen");

            /// <summary>Invertibility.</summary>
            public static readonly EntryId Invertible = new("linalg.det.invertible");

            /// <summary>Orthogonal matrices.</summary>
            public static readonly EntryId Orthogonal = new("linalg.det.orthogonal");

            /// <summary>Repeated or zero rows.</summary>
            public static readonly EntryId RepeatedRow = new("linalg.det.repeated-row");

            /// <summary>Row replacement.</summary>
            public static readonly EntryId RowReplace = new("linalg.det.row-replace");

            /// <summary>Scaling a row.</summary>
            public static readonly EntryId RowScale = new("linalg.det.row-scale");

            /// <summary>Swapping rows.</summary>
            public static readonly EntryId RowSwap = new("linalg.det.row-swap");

            /// <summary>Triangular matrices.</summary>
            public static readonly EntryId Triangular = new("linalg.det.triangular");

            /// <summary>Geometric meaning of the determinant.</summary>
            public static readonly EntryId Volume = new("linalg.det.volume");
        }

        /// <summary>Linear systems.</summary>
        public static class Sys
        {
            /// <summary>Cramer's rule.</summary>
            public static readonly EntryId Cramer = new("linalg.sys.cramer");

            /// <summary>Homogeneous systems.</summary>
            public static readonly EntryId Homogeneous = new("linalg.sys.homogeneous");

            /// <summary>Consistency (Rouché–Capelli).</summary>
            public static readonly EntryId RoucheCapelli = new("linalg.sys.rouche-capelli");

            /// <summary>Elementary row operations preserve solutions.</summary>
            public static readonly EntryId RowOps = new("linalg.sys.row-ops");

            /// <summary>Uniqueness of the reduced row echelon form.</summary>
            public static readonly EntryId RrefUnique = new("linalg.sys.rref-unique");

            /// <summary>Number of solutions.</summary>
            public static readonly EntryId SolutionCount = new("linalg.sys.solution-count");

            /// <summary>Structure of solutions.</summary>
            public static readonly EntryId Structure = new("linalg.sys.structure");
        }
    }

    /// <summary>Trigonometry.</summary>
    public static class Trigonometry
    {
        /// <summary>Trigonometric equations.</summary>
        public static class Eqn
        {
            /// <summary>Basic cosine equation.</summary>
            public static readonly EntryId Cos = new("trig.eqn.cos");

            /// <summary>Basic cotangent equation.</summary>
            public static readonly EntryId Cot = new("trig.eqn.cot");

            /// <summary>Basic sine equation.</summary>
            public static readonly EntryId Sin = new("trig.eqn.sin");

            /// <summary>Basic tangent equation.</summary>
            public static readonly EntryId Tan = new("trig.eqn.tan");
        }
    }
}

/// <summary>Handles of the catalog entries of kind formula.</summary>
public static class Formulas
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Equations.</summary>
        public static class Eq
        {
            /// <summary>Linear equation.</summary>
            public static readonly EntryId Linear = new("alg.eq.linear");
        }

        /// <summary>Percents.</summary>
        public static class Pct
        {
            /// <summary>Percent change.</summary>
            public static readonly EntryId Change = new("alg.pct.change");
        }

        /// <summary>Partial fractions.</summary>
        public static class Pf
        {
            /// <summary>Distinct linear factors.</summary>
            public static readonly EntryId DistinctLinear = new("alg.pf.distinct-linear");

            /// <summary>Irreducible quadratic factor.</summary>
            public static readonly EntryId Quadratic = new("alg.pf.quadratic");

            /// <summary>Repeated linear factor.</summary>
            public static readonly EntryId RepeatedLinear = new("alg.pf.repeated-linear");
        }

        /// <summary>Quadratics.</summary>
        public static class Quad
        {
            /// <summary>Axis of symmetry.</summary>
            public static readonly EntryId Axis = new("alg.quad.axis");

            /// <summary>Quadratic from its roots.</summary>
            public static readonly EntryId FromRoots = new("alg.quad.from-roots");

            /// <summary>Quadratic formula.</summary>
            public static readonly EntryId QuadraticFormula = new("alg.quad.quadratic-formula");

            /// <summary>Vertex form.</summary>
            public static readonly EntryId VertexForm = new("alg.quad.vertex-form");
        }

        /// <summary>Variation.</summary>
        public static class Var
        {
            /// <summary>Direct variation.</summary>
            public static readonly EntryId Direct = new("alg.var.direct");

            /// <summary>Inverse variation.</summary>
            public static readonly EntryId Inverse = new("alg.var.inverse");

            /// <summary>Joint variation.</summary>
            public static readonly EntryId Joint = new("alg.var.joint");
        }
    }

    /// <summary>Calculus.</summary>
    public static class Calculus
    {
        /// <summary>Derivative definition and rules.</summary>
        public static class Deriv
        {
            /// <summary>Parametric derivative.</summary>
            public static readonly EntryId Parametric = new("calc.deriv.parametric");

            /// <summary>Slope of a polar curve.</summary>
            public static readonly EntryId Polar = new("calc.deriv.polar");
        }

        /// <summary>Integration techniques.</summary>
        public static class Int
        {
            /// <summary>Reduction formula for cos^n.</summary>
            public static readonly EntryId ReduceCos = new("calc.int.reduce-cos");

            /// <summary>Reduction formula for (ln x)^n.</summary>
            public static readonly EntryId ReduceLn = new("calc.int.reduce-ln");

            /// <summary>Reduction formula for sec^n.</summary>
            public static readonly EntryId ReduceSec = new("calc.int.reduce-sec");

            /// <summary>Reduction formula for sin^n.</summary>
            public static readonly EntryId ReduceSin = new("calc.int.reduce-sin");

            /// <summary>Reduction formula for tan^n.</summary>
            public static readonly EntryId ReduceTan = new("calc.int.reduce-tan");

            /// <summary>Reduction formula for x^n e^x.</summary>
            public static readonly EntryId ReduceXExp = new("calc.int.reduce-x-exp");
        }
    }

    /// <summary>LinearAlgebra.</summary>
    public static class LinearAlgebra
    {
        /// <summary>Determinants.</summary>
        public static class Det
        {
            /// <summary>2×2 determinant.</summary>
            public static readonly EntryId _2x2 = new("linalg.det.2x2");

            /// <summary>Vandermonde determinant.</summary>
            public static readonly EntryId Vandermonde = new("linalg.det.vandermonde");
        }
    }

    /// <summary>Trigonometry.</summary>
    public static class Trigonometry
    {
        /// <summary>Angle units and circular measure.</summary>
        public static class Unit
        {
            /// <summary>Arc length.</summary>
            public static readonly EntryId ArcLength = new("trig.unit.arc-length");

            /// <summary>Degrees to radians.</summary>
            public static readonly EntryId DegToRad = new("trig.unit.deg-to-rad");

            /// <summary>Degrees, minutes, seconds.</summary>
            public static readonly EntryId Dms = new("trig.unit.dms");

            /// <summary>Sector area.</summary>
            public static readonly EntryId SectorArea = new("trig.unit.sector-area");
        }
    }
}

/// <summary>Handles of the catalog entries of kind pattern.</summary>
public static class Patterns
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Factoring.</summary>
        public static class Factor
        {
            /// <summary>Difference of cubes.</summary>
            public static readonly EntryId DiffCubes = new("alg.factor.diff-cubes");

            /// <summary>Difference of n-th powers.</summary>
            public static readonly EntryId DiffPowers = new("alg.factor.diff-powers");

            /// <summary>Difference of squares.</summary>
            public static readonly EntryId DiffSquares = new("alg.factor.diff-squares");

            /// <summary>Greatest common factor.</summary>
            public static readonly EntryId Gcf = new("alg.factor.gcf");

            /// <summary>Perfect-square trinomial (difference).</summary>
            public static readonly EntryId PerfectSquareMinus = new("alg.factor.perfect-square-minus");

            /// <summary>Perfect-square trinomial (sum).</summary>
            public static readonly EntryId PerfectSquarePlus = new("alg.factor.perfect-square-plus");

            /// <summary>Quadratic in form.</summary>
            public static readonly EntryId QuadraticInForm = new("alg.factor.quadratic-in-form");

            /// <summary>Monic trinomial.</summary>
            public static readonly EntryId SimpleTrinomial = new("alg.factor.simple-trinomial");

            /// <summary>Sophie Germain identity.</summary>
            public static readonly EntryId SophieGermain = new("alg.factor.sophie-germain");

            /// <summary>Sum of cubes.</summary>
            public static readonly EntryId SumCubes = new("alg.factor.sum-cubes");

            /// <summary>Sum of odd powers.</summary>
            public static readonly EntryId SumOddPowers = new("alg.factor.sum-odd-powers");
        }
    }
}

/// <summary>Handles of the catalog entries of kind method.</summary>
public static class Methods
{
    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Equations.</summary>
        public static class Eq
        {
            /// <summary>Absolute-value equations.</summary>
            public static readonly EntryId Abs = new("alg.eq.abs");

            /// <summary>Exponential equations.</summary>
            public static readonly EntryId Exponential = new("alg.eq.exponential");

            /// <summary>Solve a literal equation for a variable.</summary>
            public static readonly EntryId Literal = new("alg.eq.literal");

            /// <summary>Logarithmic equations.</summary>
            public static readonly EntryId Logarithmic = new("alg.eq.logarithmic");

            /// <summary>Equations quadratic in form.</summary>
            public static readonly EntryId QuadraticInForm = new("alg.eq.quadratic-in-form");

            /// <summary>Radical equations.</summary>
            public static readonly EntryId Radical = new("alg.eq.radical");

            /// <summary>Rational equations.</summary>
            public static readonly EntryId Rational = new("alg.eq.rational");

            /// <summary>Solve by factoring.</summary>
            public static readonly EntryId ZeroProductSolve = new("alg.eq.zero-product-solve");
        }

        /// <summary>Factoring.</summary>
        public static class Factor
        {
            /// <summary>AC method.</summary>
            public static readonly EntryId AcMethod = new("alg.factor.ac-method");

            /// <summary>Factor by grouping.</summary>
            public static readonly EntryId Grouping = new("alg.factor.grouping");

            /// <summary>Factorization over the rationals.</summary>
            public static readonly EntryId OverQ = new("alg.factor.over-q");

            /// <summary>Square-free factorization (Yun).</summary>
            public static readonly EntryId SquareFree = new("alg.factor.square-free");
        }

        /// <summary>Inequalities.</summary>
        public static class Ineq
        {
            /// <summary>Sign chart.</summary>
            public static readonly EntryId SignChart = new("alg.ineq.sign-chart");
        }

        /// <summary>Partial fractions.</summary>
        public static class Pf
        {
            /// <summary>Heaviside cover-up.</summary>
            public static readonly EntryId CoverUp = new("alg.pf.cover-up");
        }

        /// <summary>Polynomial division and roots.</summary>
        public static class Poly
        {
            /// <summary>Euclidean algorithm for polynomials.</summary>
            public static readonly EntryId Gcd = new("alg.poly.gcd");

            /// <summary>Polynomial long division.</summary>
            public static readonly EntryId LongDivision = new("alg.poly.long-division");

            /// <summary>Synthetic division.</summary>
            public static readonly EntryId SyntheticDivision = new("alg.poly.synthetic-division");
        }

        /// <summary>Quadratics.</summary>
        public static class Quad
        {
            /// <summary>Completing the square.</summary>
            public static readonly EntryId CompletingTheSquare = new("alg.quad.completing-the-square");
        }

        /// <summary>Rational expressions.</summary>
        public static class Rat
        {
            /// <summary>Simplify a complex fraction.</summary>
            public static readonly EntryId ComplexFraction = new("alg.rat.complex-fraction");

            /// <summary>Least common denominator.</summary>
            public static readonly EntryId Lcd = new("alg.rat.lcd");
        }

        /// <summary>Systems of equations.</summary>
        public static class Sys
        {
            /// <summary>Elimination method.</summary>
            public static readonly EntryId Elimination = new("alg.sys.elimination");

            /// <summary>Substitution method.</summary>
            public static readonly EntryId Substitution = new("alg.sys.substitution");
        }
    }

    /// <summary>Calculus.</summary>
    public static class Calculus
    {
        /// <summary>Derivative definition and rules.</summary>
        public static class Deriv
        {
            /// <summary>Implicit differentiation.</summary>
            public static readonly EntryId Implicit = new("calc.deriv.implicit");

            /// <summary>Logarithmic differentiation.</summary>
            public static readonly EntryId Logarithmic = new("calc.deriv.logarithmic");
        }

        /// <summary>Integration techniques.</summary>
        public static class Int
        {
            /// <summary>LIATE heuristic.</summary>
            public static readonly EntryId Liate = new("calc.int.liate");

            /// <summary>Partial fractions.</summary>
            public static readonly EntryId PartialFractions = new("calc.int.partial-fractions");

            /// <summary>Tabular integration.</summary>
            public static readonly EntryId Tabular = new("calc.int.tabular");

            /// <summary>Even powers of sine and cosine.</summary>
            public static readonly EntryId TrigEven = new("calc.int.trig-even");

            /// <summary>Odd power of cosine.</summary>
            public static readonly EntryId TrigOddCos = new("calc.int.trig-odd-cos");

            /// <summary>Odd power of sine.</summary>
            public static readonly EntryId TrigOddSin = new("calc.int.trig-odd-sin");

            /// <summary>Trigonometric substitution for sqrt(x² − a²).</summary>
            public static readonly EntryId TrigSubSec = new("calc.int.trig-sub-sec");

            /// <summary>Trigonometric substitution for sqrt(a² − x²).</summary>
            public static readonly EntryId TrigSubSin = new("calc.int.trig-sub-sin");

            /// <summary>Trigonometric substitution for sqrt(a² + x²).</summary>
            public static readonly EntryId TrigSubTan = new("calc.int.trig-sub-tan");

            /// <summary>Tangent and secant powers.</summary>
            public static readonly EntryId TrigTanSec = new("calc.int.trig-tan-sec");

            /// <summary>Weierstrass substitution.</summary>
            public static readonly EntryId Weierstrass = new("calc.int.weierstrass");
        }

        /// <summary>Limits.</summary>
        public static class Lim
        {
            /// <summary>Exponential indeterminate forms.</summary>
            public static readonly EntryId LogTrick = new("calc.lim.log-trick");
        }

        /// <summary>Taylor series.</summary>
        public static class Series
        {
            /// <summary>Series by arithmetic.</summary>
            public static readonly EntryId SeriesArithmetic = new("calc.series.series-arithmetic");
        }
    }

    /// <summary>LinearAlgebra.</summary>
    public static class LinearAlgebra
    {
        /// <summary>Determinants.</summary>
        public static class Det
        {
            /// <summary>Fraction-free elimination (Bareiss).</summary>
            public static readonly EntryId Bareiss = new("linalg.det.bareiss");

            /// <summary>Rule of Sarrus.</summary>
            public static readonly EntryId Sarrus = new("linalg.det.sarrus");
        }

        /// <summary>Linear systems.</summary>
        public static class Sys
        {
            /// <summary>Gauss–Jordan elimination.</summary>
            public static readonly EntryId GaussJordan = new("linalg.sys.gauss-jordan");

            /// <summary>Gaussian elimination.</summary>
            public static readonly EntryId Gaussian = new("linalg.sys.gaussian");
        }
    }
}

/// <summary>Handles of the catalog entries of kind convention.</summary>
public static class Conventions
{
    /// <summary>Order of operations.</summary>
    public static readonly EntryId OrderOfOperations = new("conv.order-of-operations");

    /// <summary>0^0 = 1.</summary>
    public static readonly EntryId ZeroToTheZero = new("conv.zero-to-the-zero");

    /// <summary>Real odd roots.</summary>
    public static readonly EntryId RealOddRoot = new("conv.real-odd-root");

    /// <summary>Bare log is base 10.</summary>
    public static readonly EntryId BareLogBase10 = new("conv.bare-log-base-10");

    /// <summary>Rounding for display.</summary>
    public static readonly EntryId Rounding = new("conv.rounding");

    /// <summary>Decimal literals are exact.</summary>
    public static readonly EntryId DecimalExact = new("conv.decimal-exact");

    /// <summary>Range of arccot.</summary>
    public static readonly EntryId ArccotRange = new("conv.arccot-range");

    /// <summary>Algebra.</summary>
    public static class Algebra
    {
        /// <summary>Consequences of the field axioms.</summary>
        public static class Prop
        {
            /// <summary>Division by zero is undefined.</summary>
            public static readonly EntryId DivByZero = new("alg.prop.div-by-zero");
        }
    }
}
