<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="../../src/Mathesis.Numerics/Mathesis.Numerics.csproj" />
    <ProjectReference Include="../Mathesis.Testing/Mathesis.Testing.csproj" />
  </ItemGroup>

</Project>
